# Generated by Django 4.0.1 on 2022-04-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perfil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDocumento', models.CharField(max_length=20)),
                ('TipoDocumento', models.CharField(max_length=2)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('numeroCelular', models.CharField(max_length=10)),
                ('id_Perfiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.catalogo_perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('horasMensualFormacion', models.IntegerField(null=True)),
                ('id_Instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.instructores')),
            ],
        ),
    ]
