# Generated by Django 4.0.1 on 2022-04-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='supervisora',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
