# Generated by Django 4.1 on 2022-08-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contratacion_supervisora'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichasCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=10)),
                ('FechaInicioEtapaLectiva', models.DateField()),
                ('FechaFinEtapaLectiva', models.DateField()),
                ('Jornada', models.CharField(max_length=10)),
                ('CantidadAprendices', models.IntegerField()),
            ],
        ),
    ]
