# Generated by Django 4.1 on 2022-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_contratacion_horasmensualformacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratacion',
            name='supervisora',
        ),
        migrations.AlterField(
            model_name='instructores',
            name='NumeroDocumento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
