# Generated by Django 4.1 on 2022-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_contratacion_supervisora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructores',
            name='CantidadHorasFormacion',
        ),
        migrations.AddField(
            model_name='contratacion',
            name='horasMensualFormacion',
            field=models.IntegerField(null=True),
        ),
    ]
