# Generated by Django 4.1 on 2022-09-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_contratacion_supervisora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichascaracterizacion',
            name='ficha',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
