# Generated by Django 4.1 on 2022-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_fichascaracterizacion_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructores',
            name='NumeroDocumento',
            field=models.CharField(max_length=20),
        ),
    ]
