# Generated by Django 4.1 on 2022-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_instructores_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructores',
            name='NumeroDocumento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
