# Generated by Django 4.1 on 2022-10-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_instructores_numerodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructores',
            name='Fecha_Fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instructores',
            name='Fecha_Inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instructores',
            name='TipoDeContrato',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='instructores',
            name='horasMensualFormacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instructores',
            name='supervisora',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Contratacion',
        ),
    ]
